### ISSUE TITLE
feature: remove APE tags

### ISSUE THREAD

**Issue by atomGit** [nicfit/eyeD3#526] opened 2021-02-20 15:02 UTC
some mp3's contain obsolete APE tags (such can be written by mp3gain for ex.) and apparently some decoders have problems with this, plus i personally prefer 'clean' mp3's

it would be great if they could be removed, possibly both explicitly and with --remove-all

**Comment by nicfit** [comment] 2021-03-05 01:54
Duplicate of #48

**Closed as completed by nicfit** 2021-03-05 01:54 UTC
Labels: duplicate
