### ISSUE TITLE
write into FLAC files via cli

### ISSUE THREAD

**Issue by foremtehan** [nicfit/eyeD3#580] opened 2022-09-03 10:15 UTC
I use eyeD3 cli to write tags, But looks like it only working for mp3 files

`eyeD3 --artist "My Artist" 01 A Million Miles Away.flac`

I won't get any error but tags never written. same for m4a files.

**Comment by nicfit** [comment] 2022-09-04 21:48
eyeD3 requires understanding FLAC and m4a audio formats for this.  Duplicate of https://github.com/nicfit/eyeD3/issues/404

**Closed as completed by nicfit** 2022-09-04 21:48 UTC
